### ISSUE TITLE
Links for Prime Video Sportsbar

### ISSUE THREAD

**Issue by ghost** [picons/picons#1398]
# SNP/SRP entries

**snp.index**
```
samplechannelname=Prime Video Sportsbar HD
samplechannelname1=primevideosportsbar
samplechannelname2=primevideosportsbarhd
```

**srp.index**
```
422B_3DB8_19E_820000=samplelogoname
425A_3DB8_19E_820000=samplelogoname1
4257_3DB8_19E_820000=samplelogoname2
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
logos.zip
```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**
![primevideo](https://user-images.githubusercontent.com/35585833/233789859-0f9b6b7e-8e5d-4a60-b499-ea58b84a37bd.png)

**Comment by ghost** [comment]
https://www.satindex.de/channel/33794/

**Comment by Lexzie** [comment]
Nice try using the template for making an issue.
But you have to do it right, replace `samplelogoname` bij the name of the logo.
In this case `primevideo`, as it is already in our repo: https://github.com/picons/picons/blob/master/build-source/logos/primevideo.default.svg
So you should have done it like this:

**snp.index**

```
primevideosportsbar=primevideo
primevideosportsbarhd=primevideo
```

**srp.index**

```
422B_3DB8_19E_820000=primevideo
425A_3DB8_19E_820000=primevideo
4257_3DB8_19E_820000=primevideo
```


But are you sure you want to use the `primevideo` logo for the Prime Video Sportsbar channels?
I guess it's not the same logo, otherwise I would have added the link already.
Maybe it's like this with `SPORT` beneath the `primevideo` logo: https://videoschiri.de/wp-content/uploads/2020/10/prime-video-sport-champions-league-angebot.jpg
Found on: https://videoschiri.de/champions-league-amazon-prime-video-sport-angebote/

Can you provide a screenshot of the channel with the logo?

**Comment by ghost** [comment]
But when I turn on the transmitter, this logo is shown in white


![2560px-Amazon_Prime_Logo svg](https://user-images.githubusercontent.com/35585833/235267304-2cc62b74-30e5-4e49-9ff0-73fa1e37744d.png)

**Comment by Lexzie** [comment]
Alright, let's use that logo.
Let me make the PR.

**Comment by AbuBaniaz** [comment]
Thanks for doing that @Lexzie I'll close this issue as completed. 

@William-Richards, Please re-open if required.
