### ISSUE TITLE
Radio Cité Geneve

### ISSUE THREAD

**Issue by ghost** [picons/picons#1725]
# SNP/SRP entries

**snp.index**
```
radiocité=radiocité
```
logos.zip

[radiocitegeneve.default.svg.zip](https://github.com/picons/picons/files/13688416/radiocitegeneve.default.svg.zip)

[radiocitegeneve.light.svg.zip](https://github.com/picons/picons/files/13688421/radiocitegeneve.light.svg.zip)

```

**Comment by Lexzie** [comment]
@William-Richards Isn't this the right logo for Radio Cité (Genève)?

![afbeelding](https://github.com/picons/picons/assets/14023349/e635436c-0a93-45dd-a12d-e153fbddb3b1)

Because that is what I see on [their website](https://radiocite.ch/) and found this on their Facebook page.
Unless you want to use it for a version not especially for Genève? But I could not find another version besides this one.

**Comment by ghost** [comment]
Yes 

Thanks
