### ISSUE TITLE
 ZT Radio Inside

### ISSUE THREAD

**Issue by ghost** [picons/picons#1730]
# SNP/SRP entries

**snp.index**
```
ztradioinside=ztradioinside
```
logos.zip

[ztradioinside.default.svg.zip](https://github.com/picons/picons/files/13494538/ztradioinside.default.svg.zip)

```

**Comment by AbuBaniaz** [comment]
Is the `DAB` text meant to look like that?

![Screenshot 2023-11-28 233149](https://github.com/picons/picons/assets/6644489/c55e32b3-ed28-422b-ae5c-5f482983f7d0)

**Comment by ghost** [comment]
Unbelievable, yes there was Radio Inside in my list but it has to be called ZT Radio Inside and the logo is also different... I will correct it immediately, give me 10 minutes...

**Comment by Lexzie** [comment]
First of all: @William-Richards do you make these SVG-logos from converting them in Inkscape with Bitmap Trace?
If so, you have to check the logo because they will mostly look terrible when you convert them.

Secondly, on [the website of this radiostation](https://www.ztradioinside.ch/) I see a different logo.
I think the website is leading in this, not [Wikipedia](https://de.wikipedia.org/wiki/Radio_Inside).
![radio_inside_logo_150px](https://github.com/picons/picons/assets/14023349/61cdbcee-74fe-4c4b-8e0a-be55b210eabf)

Edit: I see you replaced it with this logo.

**Comment by Lexzie** [comment]
About the converting to SVG:
If you zoom in you'll see how bad it looks:
![afbeelding](https://github.com/picons/picons/assets/14023349/13b8e436-3db8-4862-82de-93b443e189aa)

Furthermore: You have to supply logos without background.

**Comment by ghost** [comment]
No, I have not yet worked with Adobe or Inkscape. I have always used online https://de.vectorizer.ai/. Yesterday I changed and corrected a logo myself for the first time. Spoon Radio I left you a message there. You have closed it, please read my message... I will try more and more to work like you do….

**Comment by Lexzie** [comment]
Online or not. It is probably just as worse.
I am making a good png logo for this now.

**Comment by ghost** [comment]
Many thanks :-)

**Comment by Lexzie** [comment]
> ...Yesterday I changed and corrected a logo myself for the first time. Spoon Radio I left you a message there. You have closed it, please read my message... I will try more and more to work like you do….


I have not closed that issue. (#1767 )

**Comment by Lexzie** [comment]
I made a svg logo instead.
