### ISSUE TITLE
Multiple logo replacement request.

### ISSUE THREAD

**Issue by ghost** [picons/picons#1883]
Please reopen. I think the logo is better with a black and white background.

**Comment by AbuBaniaz** [comment]
Can you please use sensible titles.  Zip the logos and upload them as one attachment. And if possible, one issue instead of one every few minutes.

Look at this in the sense of the person committing the changes. You can either download one zip file and replace the logos as one operation,  Instead, the way you are doing this, we have to save every file, rename it, and then transfer. Every single one.

That excludes the cleaning up logos, resize to page selection that you could have done too! Nobody gets paid for this! Make it as easy as possible for the committer. PLEASE

**Comment by ghost** [comment]
I have already replaced the logos in the original opening via a zip file and only used this as a reference to the new opening of the original. I didn't know how to help... the link is always there

**Comment by AbuBaniaz** [comment]
Sorry, I am going to close all the other issues you have just opened. Please upload all the logos you want to use, correctly named, as one zip file in this issue  We will add the ones we agree with.

**Comment by William-Richards** [comment]
kanalk=kanalk

[kanalk.default.svg.zip](https://github.com/picons/picons/files/13693200/kanalk.default.svg.zip)

[kanalk.light.svg.zip](https://github.com/picons/picons/files/13693201/kanalk.light.svg.zip)

**Comment by AbuBaniaz** [comment]
Once again, please attach all the logos you want to add as replacements as one attachment. Put all of them in one folder then zip that folder and then attach it here. Do not zip every file individually.

**Comment by ghost** [comment]
[Logos.zip](https://github.com/picons/picons/files/13693512/Logos.zip)

**Comment by ghost** [comment]
Rai 3 HD
Can someone add this line to Rai 3 HD? Thanks

rai3lombardiahd=rai3hd

**Comment by AbuBaniaz** [comment]
> Rai 3 HD Can someone add this line to Rai 3 HD? Thanks
> 
> rai3lombardiahd=rai3hd

This has been done. You just missed the weekly build.

**Comment by ghost** [comment]
Okto HD
Can someone add this line to Okto HD? Thanks

okto=oktowien
oktohd=oktowien
oktotv=oktowien
oktotvhd=oktowien

**Comment by AbuBaniaz** [comment]
For pity's sake, he has raised individual issues as well. So now we have duplication and confusion.
