### ISSUE TITLE
Radio Fribourg / Freiburg

### ISSUE THREAD

**Issue by ghost** [picons/picons#1913]
> # SNP/SRP entries
> **snp.index**
> 
> ```
> radiofribourg=radiofribourg
> radiofreiburg=radiofribourg
> ```
> 
> **srp.index**
> 
> ```
> 6E1_D_1_FFFF0000=radiofribourg
> 6E0_10_1_FFFF0000=radiofribourg

> ```
> 
> logos.zip
> 
> [radiofribourg.default.svg.zip](https://github.com/picons/picons/files/13693702/radiofribourg.default.svg.zip)
> 
> [radiofribourg.light.svg.zip](https://github.com/picons/picons/files/13693704/radiofribourg.light.svg.zip)

![radiofribourg default](https://github.com/picons/picons/assets/35585833/92c375db-4ca3-41d3-9a6d-cc7d7f58ac04)

![radiofribourg light](https://github.com/picons/picons/assets/35585833/13d44b92-bfc5-4615-923f-ef6ef359d9b6)

_Originally posted by @William-Richards in https://github.com/picons/picons/issues/1728#issuecomment-1858912188_

**Comment by AbuBaniaz** [comment]
One zip fie with both logos. Repeat!

Use underscores, not colons in the service reference.  Repeat! 
You are choosing to copy and paste the reference that needs editing  instead of the one that we use. 

Why create more work? Are you doing this deliberately or you don't understand?  We have pointed you in the right direction numerous times. 

I won't be dealing with any of your issues if you are deliberately using options that create more work for others.

**Comment by ghost** [comment]
[logos.zip](https://github.com/picons/picons/files/13694035/logos.zip)

**Comment by AbuBaniaz** [comment]
Added here: https://github.com/picons/picons/commit/f413d05f7da8ac435b3b954b6f6b3711d5862413
I used the service reference I got from your lamedb file. Post back/re-open this issue if there is a problem. Or send me PM from one of the forums I am on.
