### ISSUE TITLE
Spital Radio LuZ

### ISSUE THREAD

**Issue by ghost** [picons/picons#1921]
Logo correction

[Logos.zip](https://github.com/picons/picons/files/13699227/Logos.zip)

**Comment by AbuBaniaz** [comment]
I am not seeing the difference to the default, apart from one being svg and one being png
https://github.com/picons/picons/blob/master/build-source/logos/spitalradioluz.default.svg

The light png logo is hazy/unclear. 

I take it you want a light logo added. @Lexzie can you create a light version when you get a moment please?

**Comment by ghost** [comment]
Thanks :-)

**Comment by Lexzie** [comment]
The [original logo](https://radioluz.ch/spitalradio/wp-content/uploads/2017/06/Radio-Luz-Verlaeufe-transparent-e1582190459832.png) is hazy too, so what can I do about that?
The SVG is, again, not done well converting from PNG to an SVG.

For making the logo light you just added a white background, that's not how it works. All logos should not have a background because some will build a picon with a own background.

I will have to have some more time to see if I can make something out of this.

**Deutsch**:
Das [Originallogo](https://radioluz.ch/spitalradio/wp-content/uploads/2017/06/Radio-Luz-Verlaeufe-transparent-e1582190459832.png) ist ebenfalls verschwommen, was kann ich also dagegen tun?
Die SVG-Konvertierung von PNG in SVG ist wiederum nicht gut gelungen.

Um ein 'light' Logo zu machen, haben Sie einfach einen weißen Hintergrund hinzugefügt, so funktioniert das nicht. Alle Logos sollten keinen Hintergrund haben, da einige ein Picon mit einem eigenen Hintergrund erstellen.

Ich werde noch etwas Zeit brauchen, um zu sehen, ob ich daraus etwas machen kann.

**Comment by ghost** [comment]
Ja ich weiss das inzwischen, darum muss das ein Profi machen ich kann das nicht. Oder kann es noch nicht..Auf weissem Hintergrund sieht es ok aus aber auf schwarzer Hintergrund gar nicht gut dann ist die Schrift nicht lesbar.

Translation: Yes, I know that now, that's why a professional has to do it, I can't do it. Or it can't yet... On a white background it looks ok but on a black background it doesn't look good at all then the font is not readable.

**Comment by Lexzie** [comment]
I saw a new logo on their [website](https://radioluz.ch/), not the best one, but the svg was also a poorly conversion from a png.
To clean that SVG and make a light variant just takes to much time.
This logo will have to do.

_Ich habe auf ihrer [Website](https://radioluz.ch/) ein neues Logo gesehen, nicht das beste, aber das SVG war auch eine schlechte Konvertierung von einem PNG.
Das SVG zu reinigen und eine leichte Variante zu erstellen, nimmt einfach zu viel Zeit in Anspruch.
Dieses Logo muss genügen._
