### ISSUE TITLE
Build log warnings

### ISSUE THREAD

**Issue by mrhotio** [picons/picons#2]
The build log currently has the following warnings:

```
This svg contains text or a png image: l1plateweg.default.svg
The following logo is an svg, but has one or more png alternatives: pfc.default.svg
The following logo is an svg, but has one or more png alternatives: rtlplus-mathecraki.white.svg
The following logo is an svg, but has one or more png alternatives: sat1.white.svg
The following logo is an svg, but has one or more png alternatives: vox.white.svg
```

**Comment by mcfly822** [comment]
These error messages are fail:
The following logo is an svg, but has one or more png alternatives: rtlplus-mathecraki.white.svg
The following logo is an svg, but has one or more png alternatives: sat1.white.svg
The following logo is an svg, but has one or more png alternatives: vox.white.svg

because there is the .default file in png (too complicated to make in svg), but the white variant are in svg (simple white shapes). I think we should do one of the following:
1. nothing 😈 
2. make the .white variant in png

**Comment by mrhotio** [comment]
pick 1, they are just informational warnings, the first one is more problematic

**Comment by mcfly822** [comment]
@hotio 1st (and 2nd) one was corrected in the commit above.
If the others are just informational, then my first plan will be activated: we do nothing ⛄️
