### ISSUE TITLE
TV8 Italy logo mismatched with TV8 Sweden in SNP version

### ISSUE THREAD

**Issue by mac84mac** [picons/picons#2047]
I don't know if in SRP version of picons everything is correct as i use only SNP version for its obvious advantages, however with many TV8 versions i noticed errors.
On satellites (13E and 9E) and also italian DVB-T  TV8 Italy gets assigned logo from TV8 Sweden
on the other hand on 0.8W there is a channel TV8 Slovakia (TV osem) which gets assigned logo from TV8 Italy
and on 42E TV8 Turkey gets also assigned logo from TV8 Italy.
Others like TV8 Lithuania on 4.8E are correct

**Comment by AbuBaniaz** [comment]
When different channels have the same snp name, we can distinguish between them by using the service references in the snp.index file. When the picons are created, they will then point to the different logo.

To my mind, we should use what is less maintenance instead of just first come first served.

It is very important to distinguish between created picon, and logo on this repository. If you get your hard around this, it is very easy to understand whet we need to do.  If people  just look at the tv8 link/logo created on receiver, they will fail to understand what needs to be done.

We have following logos:
```
tv8.default.svg
tv8-clusibroto.default.svg
tv8-cricroclot.default.svg
tv8-hilerethip.default.png
tv8int.default.png
```
This project can cater for these differences, but someone has to provide the links. Can you provide them?

https://github.com/picons/picons/blob/master/build-source/logos/tv8.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/tv8-clusibroto.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/tv8-cricroclot.default.svg
https://github.com/picons/picons/blob/master/build-source/logos/tv8-hilerethip.default.png
https://github.com/picons/picons/blob/master/build-source/logos/tv8int.default.png

**Comment by AbuBaniaz** [comment]
An example of where this is done is here

```
15_48_20_0=zoom
1CC0_13_55_300000=zoom
zoomukraina=zoom
11E4_406_1_C00000=zoom-cisarahost
177B_423_1_C00000=zoom-cisarahost
zoomhd=zoomhd
zoom=zoomtv
zoomtv=zoomtv
```

**Comment by mac84mac** [comment]
Now I understand how it works for homonymy cases and how to implement it.
Also I figured out why even if default tv8 without extension is assigned to tv8 italy it picks always swedish version logo. On line 16064 of index.snp we have tv8hd=tv8-cricroclot, as the identifier "TV8 HD" is used also by italian TV8 this rule has higher priority for the association of the logo, so i suggest removing this line should suffice to automatically have italian tv8 get correct logo without having service IDs exceptions, however if needed I can provide them
Also these lines should be added 
7A46_2CB_600_E080000=televiziaosem         (0.8W tv8 slovakia)
3BC4_A415_42E_1A40000=tv8-hilerethip      (42.0E tv8 hd  turkey)
3264_A414_42E_1A40000=tv8-hilerethip       (42.0E tv8 turkey)

so the problem with SNP is in these cases when same or similar channel identifier is used we must rely on service ID and make corrections in database when for example they change transponder or other parameters resulting in ID changing.

Since I'm a newbie I'd like someone more expert makes those edits, in the future I will probably have more confidence and do everything myself.
BTW i noticed there is also a tv8.5 which seems a sister version of tv8 turkey which as far as i could check has not a picon in our project yet.
Please let me know when changes are done so I will close the issue. (I had to learn even this last time) :-)

**Comment by AbuBaniaz** [comment]
Not quite correct, Nothing needs to be deleted. We just need to add the service reference links in the snp file.
I can't open those channels, so I cannot do this.

To rephrase the long winded way of the working/out process to solve this issue, for every channel please answer the following:

```
1. What is snp name of channel? Answer  is "tv8"
2. What is the trimmed service reference (as used by this repository) of the channel?
3. What is the name of the logo on this repository that you want to use for the picon?
```
 
It appears that you have mostly understood what we need to do. If you can add the details for all the affected channels, we can correct it. The net result is that we will end up adding something like this. 
 
```
7A46_2CB_600_E080000=televiziaosem
3BC4_A415_42E_1A40000=tv8-hilerethip
3264_A414_42E_1A40000=tv8-hilerethip
```

**Comment by mac84mac** [comment]
I'm adding all service reference IDs for affected channels, today i did a new scan we have on 13E since few days another tv8 (moldova) for which we will need adding the logo and some tv8-xxxxxxxxxx reference to correctly match this station in snp version.
However I'm not convinced that line tv8hd=tv8-cricroclot should remain in index.snp as also tv8hd is used by italian tv8, but let's hear Lexzie's opinion about this issue, you said that we should go with what is less maintenance, in this case we wouldn't always have to add and correct exceptions for tv8 italy which has more IDs on satellites and is assigned the privileged tv8 without extension. This is my opinion


7A46_2CB_600_E080000=televiziaosem		    0.8W tv osem slovakia 
3BC4_A415_42E_1A40000=tv8-hilerethip           42.0E tv8 hd turkey
3264_A414_42E_1A40000=tv8-hilerethip           42.0E tv8 turkey

1C5C_1A90_FBFF_820000       13.0E tv8 italy     line around 16064 to change in snp.index it has still old ID, in srp.index is ok
46_200_1D_5A0000		9.0E tv8 italy
47_200_1D_5A0000		9.0E tv8 italy
48_200_1D_5A0000		9.0E tv8 italy
46_200_1D_EEEE0000		DVB-T Italy TV8
47_200_1D_EEEE0000		DVB-T Italy TV8
48_200_1D_EEEE0000		DVB-T Italy TV8


1B75_45_46_E080000=tv8-cricroclot     TV8 Sweden
4285_45_46_E080000=tv8-cricroclot     TV8 Sweden

6E_2FA8_13E_820000=tv8-xxxxxxxxxx    tv8 moldova 13E

tv8italy=tv8
tv8lithuania=tv8-clusibroto
tv8sweden=tv8-cricroclot
tv8turkey=tv8-hilerethip
tv8moldova=tv8-xxxxxxxxxx
tv8slovakia=televiziaosem

**Comment by Lexzie** [comment]
I have no access to Italian DVB-T and the Italy beam on 9E, so welcome for the service references.

There is no rule that a channel with the most ID's will be the one to be assigned with the snp-link.
Mostly the first time a channel named f.e. tv8hd is assigned to a logo that will be the one and all other that follow with the same name will have a srp-link. Also we'd favour 28.2/23.5/19.2/13E before other satellites and satellite before cable and DVB-T.
What could be considered is that if a station switches a lot from service reference, but the name keeps the same we could consider to favour that channel.

> On satellites (13E and 9E) and also italian DVB-T TV8 Italy gets assigned logo from TV8 Sweden on the other hand on 0.8W there is a channel TV8 Slovakia (TV osem) which gets assigned logo from TV8 Italy and on 42E TV8 Turkey gets also assigned logo from TV8 Italy. Others like TV8 Lithuania on 4.8E are correct

The name `tv8` is linked to `tv8`, which is the Italian logo.
The name `tv8hd` is linked to `tv8-cricroclot` which is the Swedish logo.

I have not done a rescan and check on 13E, and I see TV 8 (Italy) has changed 19-10-2023, so it must be longer ago since I (or for that matter anyone else) has checked or noticed this.
Like I said, I cannot receive 9E and Italian DVB-T, so if you could supply me with the lamedb file I could also check the other channels.

TV 8 Sverige (with the name `tv8hd`) is quite steady on 0.8W, so I agree to better use a srp-link for TV 8 Sverige.

`1C5C_1A90_FBFF_820000` is an old service reference for TV 8 (Italy), so I will have to do a scan of 12073 V to find out the new service reference.

For TV 8 (Moldova) I have to have the logo first and that whole transponder is new, so I will cover that in the next PR after the one for this issue.

Are the service references for 9E, DVB-T, 42E the current ones found with a scan?

**Comment by AbuBaniaz** [comment]
>There is no rule that a channel with the most ID's will be the one to be assigned with the snp-link.

True that there is no rule. But lets apply common sense and  use what is less maintenance for us.

**Comment by Lexzie** [comment]
> > There is no rule that a channel with the most ID's will be the one to be assigned with the snp-link.
> 
> True that there is no rule. But lets apply common sense and use what is less maintenance for us.

Yes, that why I said TV 8 Sverige is likely to change less from service reference, since it's been there from 19-12-2022.

I am already making the PR.

**Comment by Lexzie** [comment]
I pushed the changes (except TV8 Moldova for now), please check all the channels (not before tomorrow) and after you have done an update.

**Comment by AbuBaniaz** [comment]
We have these two entries in the snp file now. Can you please change one of them.

tv8hd=tv8-cricroclot
tv8hd=tv8

**Comment by Lexzie** [comment]
Sorry, I thought I had deleted the first one.

**Comment by Lexzie** [comment]
done...

**Comment by AbuBaniaz** [comment]
Thanks for that. 

Just for reference purpose, these are the current links
```
1C5C_1A90_FBFF_820000=tv8
tv8hd=tv8
tv8italy=tv8
2797_C9_55_300000=tv8-clusibroto
tv8lithuania=tv8-clusibroto
1B75_45_46_E080000=tv8-cricroclot
4285_45_46_E080000=tv8-cricroclot
73A_3E_46_E080000=tv8-cricroclot
tv8sweden=tv8-cricroclot
3264_A414_42E_1A40000=tv8-hilerethip
3BC4_A415_42E_1A40000=tv8-hilerethip
tv8turkey=tv8-hilerethip
4B4D_812_600_FFFF0000=tv8int
tv8int=tv8int

7604_2BE_600_E080000=televiziaosem
7A46_2CB_600_E080000=televiziaosem
BD7_AF3_BB_E080000=televiziaosem
tv8slovakia=televiziaosem
3CFD_C95_3_EB0000=televiziaosemhd
```

**Comment by Lexzie** [comment]
I deleted the TV 8 (Turkey) links for 7°E since Digitürk has left long time ago.

**Comment by AbuBaniaz** [comment]
Thank you both for the work done. I have sorted the file by logo again so the similar logos are grouped together.

**Comment by mac84mac** [comment]
Yes, the references for 9E, Italian DVB-T, 42E are fresh with a scan.
Italian channels on 9E are used for retransmission on terrestrial, so the IDs are partially similar.
I reinstalled an hour ago the ipk package with snp version of picons on my receivers now evertything is perfect associated, can't tell for srp
TV8 Italy on 13E has ID "1C5C_1A90_FBFF_820000" as I posted earlier

Now remains only this turkish TV8,5 which is 3 times on 42E with nameIDs different for SD and HD version as follows
TV8,5         3265_A414_42E_1A40000
TV8.5 HD   4077_9FC5_2A_1A40000
TV8.5 HD    3BC5_A415_42E_1A40000

**Comment by Lexzie** [comment]
Is this their logo?
![afbeelding](https://github.com/picons/picons/assets/14023349/62a38ccc-d579-4293-9d83-32746b1e5679)

**Comment by mac84mac** [comment]
Yes, however i can't find anything in vectorial format, with google image search there are better resolutions with different/inverted colors and without shadow or 3D, we can live with a bitmap for now

**Comment by Lexzie** [comment]
As far as I can find it's the only one with transparent background. I guess this one has to do...

**Comment by Lexzie** [comment]
Which name is used for TV8 (Italia) on DVB-T? It look like they all use the name `TV8 HD`?

**Comment by mac84mac** [comment]
Yes, it's used TV8 HD everywhere, 9E, 13E and DVB-T

**Comment by mac84mac** [comment]
I checked a moment ago the srp database TV8 HD Italy on 13E is missing (1C5C_1A90_FBFF_820000)

**Comment by AbuBaniaz** [comment]
> I checked a moment ago the srp database TV8 HD Italy on 13E is missing (1C5C_1A90_FBFF_820000)

Which logo on our repository do we need to assign to this service reference?

**Comment by Lexzie** [comment]
> > I checked a moment ago the srp database TV8 HD Italy on 13E is missing (1C5C_1A90_FBFF_820000)
> 
> Which logo on our repository do we need to assign to this service reference?

`tv8`

While you're adding that please change in snp.index:
`7604_2be_600_E080000=televiziaosem`
in
`7604_2BE_600_E080000=televiziaosem`

**Comment by mac84mac** [comment]
I think we can close this issue, a lot has been corrected, maybe is possible to make a quick check if other TV2, TV3 and similar are correct as this naming style is used by multiple channels in different countries, but personally I don't see mismatchings.
Thank You Lexzie and AbuBaniaz

**Comment by Lexzie** [comment]
My goal is to regularly check satellite for satellite for changes. Takes already a lot of time. Right now busy with 8°W.
I have done Allente on 0.8°W just recently.
I am not just going to check "everything".
If you point out which channels have the wrong picon, including their (stripped) service references, we will change it like you have seen in this issue.

Please make a new issue for that and please follow our guidelines or at least use the template.

**Comment by AbuBaniaz** [comment]
If raising a new issue for the mix-matches, to cut to the chase, please provide this information

What is the name of the channel?
What is the snp name of the channel?
Is the snp name already in use? Check snp.index file on this repository.

What is the service reference of the channel?
What is the trimmed reference as used by this project? See contributing to .md or the srp.index

What is the name of the logo on this repository that you **want** to use to make the picon?
