### ISSUE TITLE
Empty servicelist-tvheadend-servermode-srp.txt

### ISSUE THREAD

**Issue by CutterXYZ** [picons/picons#2395]
I'm trying to generate picons for tvheadend. I've put the tvheadend.serverconf file in /build-input/ and the first script seems to connect to my TVheadend server, but both the generated servicelist-tvheadend-servermode-srp.txt and the log file are completely empty.

I've tried on Windows (with MINGW64) and on Ubuntu, same results.

Please help.

**Comment by TheLegoBatman** [comment]
The script is probably failing because it can't find any service references. Go [here](http://localhost:9981/api/channel/grid?start=0&limit=1) on your browser and paste the output here if you like.

Edit: Or whatever ip you have tvheadend on.

Did you enable the picon settings on tvheadend? Read this again https://github.com/picons/picons?tab=readme-ov-file#piconsbuild-input

**Comment by CutterXYZ** [comment]
That was indeed the empty picon setting, thanks.
