### ISSUE TITLE
tcsport2.png is tcsport1.png and double entries

### ISSUE THREAD

**Issue by daviok** [picons/picons#24]
Hi,

There is a little problem tcsport2.png and tcsport1.png is actually the same picon as TCSport1.png
plus
tcsport1/tcsport2/tcsport3 exists already as teleclubsport1.png teleclubsport2.png teleclubsport3.png
They are some useless doubles

so please delete picons tcsport1.png and tcsport2.png
and add 

```
snp.index

teleclubsport1=teleclubsport1
tcsport1=teleclubsport1
teleclubsport2=teleclubsport2
tcsport2=teleclubsport2
teleclubsport3=teleclubsport3
tcsport3=teleclubsport3
```
Dunno if I am doing right 
thanks

**Comment by AbuBaniaz** [comment]
Hi,
Picon is the end result.  We use the links and logos to reach the end result. We can't delete any picons, only links or logos.

I cant find the links you say need deleting. I have added two new SNP links. There are no SRP links for them. It would be good to add them.

Please check what needs to be added/deleted/changed and post back.

**Comment by daviok** [comment]
tcsport2 is the same picon as tcsport1 , all 3 channels tcsport 1/2/3 are the same as teleclubsport1/2/3 which are already in the repo and well named with the right picon.
So just change tcsport2 picon cause it is tcsport1 actually

thanks

**Comment by AbuBaniaz** [comment]
You are contradicting yourself. Please post a picture showing the channel name and logo. Disable your CAM details before you take the picture.

**Comment by mrhotio** [comment]
`Dunno if I am doing right`

Wouldn't it have been better to figure it out, because it isn't making any sense now....?

This is why we expect structured data inside fenced code blocks, to take away any doubt. Putting just something wrong into code blocks, doesn't make it alright for some reason. You're just confusing people at this point.

Might have been better to ask some questions in order to better understand the concept...no?

**Comment by daviok** [comment]
nevermind so
