### ISSUE TITLE
New SLAM! logos

### ISSUE THREAD

**Issue by Varkentjes** [picons/picons#269]
# SNP/SRP entries

**snp.index**
```
slamhousuhindepauzuh=slamhousuhindepauzuh
slammixmarathon=slammixmarathon
slamtheboomroom=slamtheboomroom
```

# Logos
[slamlogos.zip](https://github.com/picons/picons/files/5123877/slamlogos.zip)

**Comment by Lexzie** [comment]
Working on it, next time for logos like slamhousuhindepauzuh and slammixmarathon also make light logos (so that they can be shown on a dark background), I made these and will commit them too:
![slamhousuhindepauzuh light](https://user-images.githubusercontent.com/14023349/91202642-69d8fb00-e702-11ea-9217-de7d684b2f27.png)
![slammixmarathon light](https://user-images.githubusercontent.com/14023349/91202652-6ba2be80-e702-11ea-98fc-1888357c994f.png)
There was also still some white background in the slamhousuhindepauzuh logo.

What's your source? Are there also logos for:
```
SLAM! 40
SLAM! Summer
SLAM! DANCE CLASSICS
SLAM! Hardstyle
SLAM! MixMarathon
SLAM! Non Stop
SLAM! Juize
```

**Comment by Lexzie** [comment]
Done
