### ISSUE TITLE
Two channel logos missing

### ISSUE THREAD

**Issue by grinsekatze003** [picons/picons#29]
Hi guys,

first at all: Awesome work, please keep it up!

I've noticed that two channel logos are missing:

1. kinomir - https://www.kinomir.tv/ - 1_0_1_CFD2_2715_F001_FFFF0000_0_0_0.png
2. halk tv - https://halktv.com.tr/ - 1_0_1_CFD3_2715_F001_FFFF0000_0_0_0.png

I'm using SNP naming convention.

Thank you!

**Comment by foxyboy69** [comment]
Ive also noticed BBC Scotland HD picon ( launched 24 February 2019 on freesat Astra 28E) )bbcscotlandhd.png is missing (SNP naming convention)
https://www.bbc.com/scotland

**Comment by Lexzie** [comment]
Could you make our lives easier by supplying the correct PNG or SVG file and link the exact name (as scanned by your receiver) linked to the logo name (for your desired snp link).

**Comment by grinsekatze003** [comment]
Sure, hope this helps:

Channel 1:
![kinomir](https://user-images.githubusercontent.com/3938620/57082673-7e1c0c00-6cf7-11e9-8665-2308a01f319b.png)
- Name (scanned by receiver): Kinomir
- 1_0_1_CFD2_2715_F001_FFFF0000_0_0_0.png
- SNP: kinomir.png

Channel 2:
![halktv](https://user-images.githubusercontent.com/3938620/57082674-7f4d3900-6cf7-11e9-98af-dd36c08bd21b.jpg)
- Name (scanned by receiver): Halk Tv
- 1_0_1_CFD3_2715_F001_FFFF0000_0_0_0.png
- SNP: halktv.png

**Comment by Lexzie** [comment]
Not 100%, if you read the [contributing guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md), you'll see the logo needs to have a transparent background and if black, you'll have to make a light version also (to be used on dark/black backgrounds).
Fortunately I have already done that a time ago for the Kino Mir logo, they are already in our database and you should have one when the name on your receiver is `kinomir` and you use snp picons.
At least I have:
![afbeelding](https://user-images.githubusercontent.com/14023349/57094288-7d43a400-6d10-11e9-8d2d-c4f9ba3e0d0a.png)

Also the naming of the logos should resemble what is readable in the logo, so in case of the logo for Halk TV, the logo should be named `halk` (and use lower case letters only).
Again, read the [contributing guidelines](https://github.com/picons/picons/blob/master/CONTRIBUTING.md) on how to name the logos and links.

Furthermore you must supply snp and/or srp links (preferably both) in this way:
**snp.index:**
```
kinomir=nashkinomir
halktv=halk
```
**srp.index:**
```
CFD2_2715_F001_FFFF0000=nashkinomir
CFD3_2715_F001_FFFF0000=halk
```

As you can see, leave out the preceeding `1_0_1_` and the `_0_0_0` at the end.
They will automatically be added when building the picons.

Because I understand that it's not that easy, I have already added the srp.link for Kino Mir for you (like I said the snp.link is already present).
But for Halk TV I need a logo with transparent background which is hard to do with the logo you supplied.
Maybe someone else like @TheLegoBatman or @mcfly822 likes to do it?
Or try to find a logo with transparent background, preferably a SVG/vector image or a PNG with high resolution.

**Comment by Lexzie** [comment]
I have managed to remove the white background myself and added the logo and links.

**Comment by dalmore72** [comment]
link for svg logo kinomir

https://content4tv.com/wp-content/uploads//2017/08/KINOMIR.svg

**Comment by grinsekatze003** [comment]
Wow, you're awesome @Lexzie! Please keep up the great work and many thanks!

**Comment by Lexzie** [comment]
Please leave this open, I will replace our PNG for the SVG and there was still the question about a BBC Scotland HD logo.
Maybe tonight I have time to do that.

**Comment by TheLegoBatman** [comment]
The BBC Scotland HD logo is present and is linked in the snp index.

**Comment by Jasmeet181** [comment]
The Content4TV Nash Kinomir logo isn't the best, i cleaned it up a bit when I used it
https://raw.githubusercontent.com/Jasmeet181/mediaportal-ru-logos/master/TV/Source/Nash%20Kinomir.svg
https://raw.githubusercontent.com/Jasmeet181/mediaportal-ru-logos/master/TV/Source/Nash%20Kinomir%20-%20Dark.svg

For future reference, YouTube logos loose transparency when they're upscaled e.g.
Upscaled: https://yt3.ggpht.com/a/AGF-l7-K1iwOHrurtYU4fPlWSS3eG2jTPybwLeFz7Q=s900-mo-c-c0xffffffff-rj-k-no
Original: https://yt3.ggpht.com/a/AGF-l7-K1iwOHrurtYU4fPlWSS3eG2jTPybwLeFz7Q

**Comment by Lexzie** [comment]
By adding the SVG logo of course I mean first cleaning up the logo.
I also saved them as optimized SVG's.

What exactly do you mean about upscaled logo's?

**Comment by Jasmeet181** [comment]
The Halk TV logo is 512x512px with the equal sign and everything to right of it removed from the URL. The 's900' part was scaling it up to 900px, you can change it another number. I was wrong though it's the '-rj' part that flattens it.

Did you notice a difference with Inkscape's optimization? I can see that the IDs are stripped in your and only shortened in mine. I recently made some changes to my optimization script to try and match the recommendations in the picons wiki.

**Comment by Lexzie** [comment]
About SVG-files, this is what I do:
I open them in Inkscape, select all, size it up too 800 pixels, resize page to fit the picture (ctrl-R) and save them as optimized SVG the way others here have explained to me.
You made a script for that?

About the Halk TV logo: I just copy-pasted the picture from here and edited it to remove the background. I'll have to try on a PC what you explained.

**Comment by Lexzie** [comment]
I tried your tip for removing the background on YouTube logo's and when I remove the ending '-rj-k-no' it works great!
Although the question rises if and how much you can upscale it without loss of quality?
Just resizing a bitmap picture will not make it better, but in this case it does!
So I guess the source is probably not a bitmap picture.

**Comment by Jasmeet181** [comment]
You can go up to [10000](https://yt3.ggpht.com/a/AGF-l7-K1iwOHrurtYU4fPlWSS3eG2jTPybwLeFz7Q=s10000-mo-c-c0xffffffff-k-no), sometimes slightly less. I think they use [RAISR](https://ai.googleblog.com/2016/11/enhance-raisr-sharp-images-with-machine.html), while I'd agree that your replacement Halk TV logo looks better than if similarly scaled in GIMP etc., I can see some blurriness and jagged edges. The [YouTube channel icon specs](https://support.google.com/youtube/answer/2976309?hl=en-GB) list:
- JPG, GIF, BMP or PNG file (no animated GIFs)
- 800 x 800 px image (recommended)

I only scripted the optimization part since it's quite cumbersome in Inkscape and just uses Scour, I also have some other things to run at the same time from the LogoManager developers.

**Comment by Lexzie** [comment]
I don't know exactly what Scour is, but it probably means I can't use the script.

**Comment by Jasmeet181** [comment]
It's a Python SVG optimizer
https://github.com/scour-project/scour

The documentation was published recently
https://github.com/scour-project/scour/wiki/Documentation

**Comment by mrhotio** [comment]
When using scour....be sure that the output still works with rsvg.

**Comment by Lexzie** [comment]
I guess all is said and done her....
