### ISSUE TITLE
srp.index changes for CNN/PBS America/FreeSports HD and some new SRPs

### ISSUE THREAD

**Issue by anthonykelly** [picons/picons#42]
The following lines need to be **modified** in `srp.index`:
```
C48C_811_2_11A0000=cnn
D016_83F_2_11A0000=pbsamerica
CD5F_844_2_11A0000=freesportshd
```

The following lines need to be **added** to `srp.index`:
```
C4EB_813_2_11A0000=gemstv
CFE1_83F_2_11A0000=thevault
D760_82F_2_11A0000=transworldrtadio
D75F_82F_2_11A0000=virginradio
```

**Comment by AbuBaniaz** [comment]
A modification is a combination of addition and deletion. It would be appreciated if you could list the additions and deletions separately to save deciphering what is implied. Otherwise please just list what needs to be added. When more than one service references exist, the first  one at the top is used.

I have added the references
