### ISSUE TITLE
New Logo for some Football Clubs TV

### ISSUE THREAD

**Issue by luka838** [picons/picons#485]
# SNP/SRP entries

**snp.index**
```
realmadridtv=realmadridtv
intertv=intertv
romatv=romatv

```

**srp.index**
```
7798_424_1_C00000=realmadridtv
250F_189C_FBFF_820000=intertv
10A8_2198_FBFF_820000=romatv
```

_Make sure you replace the above sample data with the actual data you want added._

# Logos
Real Madrid TV new logo
https://www.euskaltel.com/bundles/app/images/channels/realmadridtv_200x200.png

Inter TV
https://twitter.com/Inter_TV/photo

Roma TV
https://it.wikipedia.org/wiki/Roma_TV#/media/File:ROMA_TV_2020_-_2021.svg

**Comment by Lexzie** [comment]
Very nice, unfortunately the logos for Real Madrid and Inter TV are too small to use. I couldn't find logos in better quality.
I hope you, or someone else, can find better logos. Preferably SVG (like Roma TV) or with much more resolution/pixels.

Are you sure the logo for Inter TV is the one used on screen?
Because I keep finding this one, even on their own website: https://static.wikia.nocookie.net/logopedia/images/1/1a/1920px-Inter_TV_-_Logo_2017.svg.png/revision/latest?cb=20200504230509

The snp links for Real Madrid TV and Roma TV and the srp.link for Real Madrid TV are already okay, so if we can find a better logo for Inter TV and Real Madrid TV, we only need to add/change these links:

**Add in snp.index**
```
intertv=intertv
```  


**Replace in srp.index**
```
2CC0_2580_FBFF_820000=interchannel
```
for
```
250F_189C_FBFF_820000=intertv
```

I already submitted the logo and links for Roma TV.

**Comment by luka838** [comment]
thank you for adding 
for Inter TV I think I watch Inter TV with IPTV and it had that new logo but I'm not 100% sure
here this big logo that I made from this source
https://image.discovery.indazn.com/eu/v2/eu/image?id=372810821429_image-header_pIt_1610813920000&quality=70

![image-removebg-preview](https://user-images.githubusercontent.com/70975338/108376402-a4cc6f00-720b-11eb-8a28-8ed8659a6cc3.png)
 
 for Real Madrid TV this logo is used by movistarplus.es site and various Spanish TVGuide sites like tvguia.es
 https://www.movistarplus.es/canal/real-madrid-tv?id=REALM
 https://www.tvguia.es/tv/programacion-real-madrid-tv

**Comment by luka838** [comment]
update: 
I just watch Inter TV with IPTV service and I took Snapshot
![INTER TV](https://user-images.githubusercontent.com/70975338/108382023-10fda180-7211-11eb-83b1-eee95c48d8ed.png)

If you want delay it little bit until they change INTER MILAN name and badge all together
https://onefootball.com/en/news/all-change-inter-to-implement-new-name-and-badge-in-march-32188192

**Comment by Lexzie** [comment]
The logo you made has still bad edges, it should be totally white and after that you have to make a dark variant too.
I might be able to build that logo in Inkscape if I should have a svg-version of the Inter Milan logo.

The Real Madrid logos you pointed to are even worse.

**Comment by qosobrin** [comment]
There it goes my contribution to this case.

[realmadridtv.zip](https://github.com/picons/picons/files/6018245/realmadridtv.zip)

Regards.

**Comment by Lexzie** [comment]
Thank you very much @qosobrin Did you made that yourself?
Good work.

And I made the Inter TV logo.
