### ISSUE TITLE
Suggestion about Finnish HD channels

### ISSUE THREAD

**Issue by FunctionalHacker** [picons/picons#49]
The Finnish television network will depreceate all non-HD channels pretty soon. And as of now, in the picons repository there are only 4 channels that have a "HD" logo. These are:
```
build-source/logos/yletv1hd.default.svg
build-source/logos/yletv2hd.default.svg
build-source/logos/mtv3hd.default.svg
build-source/logos/yleteemajafemhd.default.png
```

So, since these channels will be "normal" channels soon, I suggest  we point the existing indexes for these HD channels to their non-HD counterparts (just remove hd from the name).

There's also a lot of missing indexes. I had to build my index by hand because of this. But I will open another issue for that soon.

**Comment by mrhotio** [comment]
When they are deprecated this can be done, or now if it'll happen soon.

If you are able to, we'd rather have you submitting issues according to the guidelines....no need for lenghty stories, when short correct mutations in code blocks are easier to read....additions to the top will override older entries, so most everything can be fixed by piling on top.

Even better would PR if you comprehend git.

Thanks for your input.

**Comment by FunctionalHacker** [comment]
The transition will happen on march 31st, 2020 so I would say pretty soon. I can submit the PR if you would like to go ahead with this.

**Comment by mrhotio** [comment]
no, that's not pretty soon, that's months away

**Comment by FunctionalHacker** [comment]
Okay now that I think about this more it might be better to wait and see how the transition goes and then do the change.

I will close this now and then submit a PR next year.

**Comment by mrhotio** [comment]
that would indeed be the best solution, otherwise we might aswell delete all logos, because sometime in the future every channel will dissapear :-)
