### ISSUE TITLE
new Discovery Channel logo

### ISSUE THREAD

**Issue by mcfly822** [picons/picons#52]
I'd like to upload this new logo, but don't know for which channels to use.
And I'm also confused about the filename. Delete old logo and use the same filename? Or create a new filename? Any suggestions are welcome 😺 
[discoverychannel2019.zip](https://github.com/picons/picons/files/3611850/discoverychannel2019.zip)

**Comment by Lexzie** [comment]
I could only see that Discovery Channel Deutschland changed the logo (besides the channels I couldn't check, see below).
So that would be:
```
4EF3_21FC_9C_5A0000
82_6_85_C00000
```
They use the names `Discovery HD` and `Discovery Channel HD`, so that's very common and you should also use the srp-links in snp.index.

Any other versions you know already use the new logo?

**I checked these versions and they all had still the old logo:**
Discovery Channel Srbija
Discovery Channel Bulgaria
Discovery Channel Central Europe
Discovery Channel Romania
Discovery Channel UK/Discovery Channel Ireland
Discovery Channel Nederland
Discovery Channel Iberia
Discovery Channel Norway
Discovery Channel Denmark
Discovery Channel Sweden
Discovery Channel Finland
Discovery Channel Hungary
Discovery Channel France (although still old logo on https://discoveryfrance.fr/)
Discovery Channel Italia (although still old logo on https://discoverychannel.it/)
Discovery Channel Russia (although still old logo on http://www.discoverychannel.ru/)

**Couldn't check:**
Discovery Channel Türkiye (maybe later)
Discovery Channel Middle East & Africa

**Comment by mcfly822** [comment]
Thank @Lexzie !
I will add your references, and maybe some other.
The new logo will be active on next monday in Hungary. Maybe in other countires in this region also will use the new logo.
I still don't know how to name this file. New name or delete the old discovery logo and use its name?

**Comment by mrhotio** [comment]
pick a new name until all channels have switched to the new logo

**Comment by Lexzie** [comment]
Looks like more (all?) versions have changed to the new logo.

Besides:
Discovery Channel France (still old logo on https://discoveryfrance.fr/)
Discovery Channel Russia (still old logo on http://www.discoverychannel.ru/)

Couldn't check:
Discovery Channel Türkiye
Discovery Channel Middle East & Africa

**Comment by Lexzie** [comment]
Discovery Channel Russia (according to their [website](http://www.discoverychannel.ru/)) is changed too.
France still isn't.

**Comment by mcfly822** [comment]
@hotio @Lexzie Thank you!

**Comment by Lexzie** [comment]
I've noticed that a lot of links still link to the old Discovery logos.
There's also a HD logo in use, I have to make that one.
Still work to do.
