### ISSUE TITLE
Missing Switzerland (CH) only channels

### ISSUE THREAD

**Issue by mountainash** [picons/picons#62]
The following channel icons aren't include (and should be - if the mod wants???):

- [ ] TeleBärn - https://www.telebaern.tv/
- [ ] TeleBasel - https://telebasel.ch/
- [ ] Tele M1 - https://www.telem1.ch/
- [ ] Tele Top - https://www.toponline.ch/tele-top/
- [ ] TV Ostschweiz (TVO) - http://www.tvo-online.ch/

**Comment by Lexzie** [comment]
Take a moment and read the guidelines in [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)

Please supply the downloaded logos, preferably svg's or png's (high res).
But without links to the servicename and/or service reference we cannot add them.

I'm happy to help you, as long as you do some effort too.

**Comment by Lexzie** [comment]
I already found the logos, please confirm that they are the right ones:
https://de.wikipedia.org/wiki/Datei:TeleB%C3%A4rn_Logo.svg
https://upload.wikimedia.org/wikipedia/commons/7/7a/Telebasel_Logo.png
I'd better combine these svg's:
https://telebasel.ch/wp-content/themes/telebasel-theme/img/menu-open.svg
https://telebasel.ch/wp-content/themes/telebasel-theme/img/menu-home.svg
https://www.persoenlich.com/sites/default/files/filemanager/M1Logos.png
(The right one)
https://de.wikipedia.org/wiki/Datei:Logo_Tele_Top.svg
https://upload.wikimedia.org/wikipedia/commons/9/92/Tvo_logo.svg

But still absolutely necessary is a list of servicenames (the names how your receiver scans the stations) for snp-picons and/or the service references for srp-picons.

**Comment by mountainash** [comment]
The [M1 logo](https://www.persoenlich.com/sites/default/files/filemanager/M1Logos.png) is the one on the right side.

I'm not sure on the snp/srp names as I don't think these are satellite channels - more for other services that also use the icons from this repo.

[Init7.ch](https://api.init7.net/fiber7-tv-channels.json) is using the names:
-  `TeleBaern`
-  `TeleBasel`
-  `TeleM1`
-  `TeleTop`
-  `TVO`

[Zattoo.com](https://zattoo.com/zapi/v2/channels) is using the names:
-  `telebaern`
-  `telebasel`
-  `telem1`
-  `tele_top`
-  `teleostschweiz`

**Comment by Lexzie** [comment]
I'm wondering: Do you receive these channels yourself?
If so, please supply your channel names and/or service references. If you have a Enigma2 receiver, you can read out the database with f.e. Dreamset and export the names and references with that.

But I'm also wondering if you read the [contribution rules](https://github.com/picons/picons/blob/master/CONTRIBUTING.md), or if you understood them.

**You should submit an issue like this:**
First download the logos (preferably svg, otherwise png with high quality).
If you can edit the logos to the requirements:
-Transparent background
-No free space around the logo
-If (part) of the logo is very dark, also submit a light version and if light a dark version.
-Name the files <name visible in logo*>.default.<svg|png> and (if you have both a dark (=default) and light version) <name visible in logo*>.light.<svg|png>
Make sure the logo name doesn't already exist in this repo, otherwise you should append
-Save svg's as Optimized svg's.
-No base64 image inside a svg, otherwise export them as png.
-Zip the files and submit them in an issue.

Supply links to link channel names and/or service refernces to the logos.
Place these links between three backticks (` ``` `).
Please take note in the guidelines how to define the links ("Naming").

In this case you should have submitted it f.e. like this:

**Please add these logos:**
[Swiss.zip](https://github.com/picons/picons/files/3728146/Swiss.zip)

**Please add these links to snp.index:**
```
telebaern=telebarn
telebasel=telebasel
telem1=telem1
teletop=teletop
teleostschweiz=tvo
tvo=tvo
```

As soon as I am home tonight I will upload this, but if you have more information, like the service references (if you have a Enigma2-receiver you can also upload the lamedb file if really don't understand what I'm talking about).

**Comment by mrhotio** [comment]
Please feel free to ask to re-open this issue when you feel like you are able to provide the requested info.

**Comment by mountainash** [comment]
Hello @Lexzie I don't have "Enigma2-receiver" (but that's part of the beauty of open-source - your project might not be used for the purpose you intended).

One of the great things about Github is the difference between and "issue" and a commit - one is open and one is very defined.... this is the former. I'm sorry I haven't met your expectations for raising an issue on this to this project, but I'm very gratefully that you have ran with it.

Choose whatever "Naming" you like and others will get the benefit of the logos in the repo (if someone does have changes down-the track, well, that's easily handled as well).
