### ISSUE TITLE
RTL2 Germany has a new logo

### ISSUE THREAD

**Issue by di-schi** [picons/picons#75]
![RTLZWEI_Logo_2019](https://user-images.githubusercontent.com/34864813/67520062-6c189600-f6a8-11e9-9bc9-c9dc2aee1228.png)

**Comment by di-schi** [comment]
https://de.wikipedia.org/wiki/RTL_II#/media/Datei:RTLZWEI_Logo_2019.svg

![rtl2](https://user-images.githubusercontent.com/34864813/67521354-feba3480-f6aa-11e9-9e15-0a32b4bef04c.png)

**Comment by Lexzie** [comment]
Not only RTL 2 Deutschland, also RTL 2 Schweiz and RTL 2 Austria changed to RTL Zwei (logically, since they are the same besides the commercials I believe).

The coloured one could do for default version (no `light` or `dark` version needed).
I will also make a `white` version, because there is one now already.
I have to find or build a `rtlzweihd` logo, because there is a HD-logo in use.
And I will check if naming (on Astra 19.2E that is) is changed.

IMO we name this logo `rtlzwei`, so that we can use the name `rtl2` for another logo, f.e. `rtl2-frakuherow`.
The logo `rtl2-wapadedrud` can be renamed to `rtlii`, since that is what is seen in the logo (and the station is called RTL II).
`rtl2-clavecloha` will keep that name.

Since this has to be done precicely I have to do this later today, probably this evening.

**Comment by mcfly822** [comment]
@Lexzie Agree 👍

**Comment by Lexzie** [comment]
Done.
commit 67223ba1c944404003ba6d32d081987b75fb531b
