### ISSUE TITLE
New Boomerang HD logo?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons#84]
Hi guys,

On Boomerang HD on Eutelsat 21A and Boomerang Polska HD (Hotbird), I saw this logo, instead of the logo now in repository:
![boomeranghd](https://user-images.githubusercontent.com/14023349/71199642-ae201b80-2296-11ea-9b71-77a5dafc4881.png)

I can't check others if they changed too, like Boomerang UK HD, Boomerang Türkiye HD or Boomerang Central & Eastern Europe HD (Nova package on Hotbird).

Can someone at least check the UK one before I replace the logo for all the versions?

**Comment by mrhotio** [comment]
The regular channel already uses that logo minus the HD, so it's safe to assume hd one will be the same, but I can't check since it isn't fta

**Comment by Jasmeet181** [comment]
I don't have access to the UK HD channel but the +1 channel has that layout instead of the pink rectangle.
![boomerangplus1](https://user-images.githubusercontent.com/14339434/71254137-efa9d880-2321-11ea-8bbf-ba4cc0136840.png)

I tried to make something similar
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/3ca4b306b7758816d49fa1019dbba99a9dad87d4/TV/Source/Boomerang%20Plus%201%20-%20Dark.svg
