### ISSUE TITLE
Service conflict rtl+ and rtlplus

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#89]
# SNP/SRP entries

**snp.index**
```
rtlplus=rtlplus
rtlplus=rtlplus-mathecraki

```

rtlplus-mathecraki is the german one ...spelled out "rtlplus"
rtlplus is the hungarian one ...spelled out rtl+

is there a way to fixe this?

**Comment by AbuBaniaz** [comment]
The way to fix it is for one of them to use a service reference. Like in SRP.index. Normally, the least frequent one uses SRP and most common one uses SNP. Reason for this is fewer updates would be required.

**Comment by Lexzie** [comment]
And that's why `2F30_441_1_C00000=rtlplus-mathecraki` is in snp.index
But `rtlplus=rtlplus-mathecraki` should not be there, but since `rtlplus=rtlplus` is above it, this still will resolve correctly.
I deleted `rtlplus=rtlplus-mathecraki`, so there will no confusion anymore.

If you have (f.e. on cable) the hungarian logo at the German RTL Plus, please supply the srp-link so we can update snp.index (and srp.index) with that link.

**Comment by SmoothMC** [comment]
here is the srp-link for rtlplus on Vodafone Cable TV
D04F_2714_F001_FFFF0000=rtlplus-mathecraki

**Comment by Lexzie** [comment]
Thank you, I will add the link asap.
Make sure in your next commit you place the link(s) between three ticks (`), separate for additions to snp.index and srp.index, as stated in the contribution guidelines.
https://github.com/picons/picons/blob/master/CONTRIBUTING.md
