### ISSUE TITLE
[QUESTION] Do white logo's fallback to a light or default version?

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons#99]
Don't know if this is an error.

when i build my picons in white the fallback logo must be the light one.  isn't it?
but so far the fallback is always the default one.  :/

**Comment by mrhotio** [comment]
No, that's how it's supposed to work.

**Comment by SmoothMC** [comment]
ok? but in in some cases we could save data and work, because the light one is already white
maybe it is an option to change it in the code...or speaks something elementary against it?

**Comment by mrhotio** [comment]
If you read the guidelines, you'll understand why a white logo can't fallback to a light logo, heck even falling back to default isn't the right thing to do, but I'm not going to modify the script and add exclusions for certain versions. If all white logos are present the problem is non-existent, which would be the end goal....
